### ISSUE TITLE
stripes pu error in log

### ISSUE THREAD

**Issue by cvanlith** [flamingo-geocms/flamingo#1319]
### Version
5.3.10

### Browser info
latest chrome

### URL
https://flamingo5.b3p.nl/viewer/app/Tailormap-Trees/v1

### Where and/or What
in the log file

### Server log
<details><summary>relevant section of the server log:</summary>

```

2019-01-10 10:34:14 ERROR net.sourceforge.stripes.util.Log.error(Log.java:82) - 
net.sourceforge.stripes.exception.StripesRuntimeException: In order to call Stripersist.getEntityManager() without any parameters there must be exactly one persistence unit defined.
	at org.stripesstuff.stripersist.Stripersist.getEntityManager(Stripersist.java:622)
	at nl.b3p.viewer.util.IPAuthenticationFilter.doFilter(IPAuthenticationFilter.java:93)


```

</details>

**Comment by mtoonen** [comment]
Config error
