### ISSUE TITLE
Updating service fails with foreign key constraint violation from configured_attribute to feature_type

### ISSUE THREAD

**Issue by matthijsln** [flamingo-geocms/flamingo#351]
```
2015-05-26 11:40:38 ERROR org.hibernate.util.JDBCExceptionReporter - Batch entry 0 delete from feature_type where id='12495' was aborted.  Call getNextException to see the cause.
2015-05-26 11:40:38 WARN  org.hibernate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23503
2015-05-26 11:40:38 ERROR org.hibernate.util.JDBCExceptionReporter - ERROR: update or delete on table "feature_type" violates foreign key constraint "fk521a69dbb7916580" on table "configured_attribute"
  Detail: Key (id)=(12495) is still referenced from table "configured_attribute".
2015-05-26 11:40:38 WARN  net.sourceforge.stripes.exception.DefaultExceptionHandler - Unhandled exception caught by the Stripes default exception handler.
javax.persistence.RollbackException: Error while committing the transaction
            at org.hibernate.ejb.TransactionImpl.commit(TransactionImpl.java:93)
            at nl.b3p.viewer.admin.stripes.GeoServiceActionBean.update(GeoServiceActionBean.java:611)
```

The foreign key from configured_attribute to feature_type was possibly added later than service updating. So maybe it should just be cleared when removing layers?

**Comment by matthijsln** [comment]
Exception was from version 4.4.8, need to verify bug exists in latest version.

**Comment by matthijsln** [comment]
Cause:

ArcGIS service has removed layer. Updating service removes layer and also its featuretype (of the feature source linked to the geoservice). This failed because the featuretype was selected as featuretype for a layer of another service.
