### ISSUE TITLE
Clicking WMTS layer in "Boomstructuur met kaarten" causes error

### ISSUE THREAD

**Issue by mprins** [flamingo-geocms/flamingo#897]
### Version
Which version of flamingo do you use: 

Git info |--
-- | --
Git branch: | impr/ext-620
Git remote url | git@github.com:flamingo-geocms/flamingo.git
Git commit abbrev id: | 0c546fa
Git commit full id: | 0c546fade01994a6c37f1a5c519b099d20e1d4b5
Git commit time: | 25.09.2017 @ 09:07:11 CEST

### URL
localhost

### Where?
viewer-admin

### What happened

After adding a WMTS layer to a new sublevel "luchtfoto" under "Achtergrond" and saving that and then clicking on the layer the following error shows

<details>
<summary>
org.json.JSONException: JSONObject["name"] not found.
</summary>

```

org.json.JSONException: JSONObject["name"] not found.
	org.json.JSONObject.get(JSONObject.java:471)
	org.json.JSONObject.getString(JSONObject.java:717)
	nl.b3p.viewer.admin.stripes.ApplicationTreeLayerActionBean.loadInfo(ApplicationTreeLayerActionBean.java:126)
	sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.lang.reflect.Method.invoke(Method.java:498)
	net.sourceforge.stripes.controller.BeforeAfterMethodInterceptor.invoke(BeforeAfterMethodInterceptor.java:154)
	net.sourceforge.stripes.controller.BeforeAfterMethodInterceptor.intercept(BeforeAfterMethodInterceptor.java:104)
	net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:173)
	org.stripesstuff.plugin.waitpage.WaitPageInterceptor.intercept(WaitPageInterceptor.java:175)
	net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:173)
	net.sourceforge.stripes.controller.ExecutionContext.wrap(ExecutionContext.java:86)
	net.sourceforge.stripes.controller.DispatcherHelper.invokeEventHandler(DispatcherHelper.java:454)
	net.sourceforge.stripes.controller.DispatcherServlet.invokeEventHandler(DispatcherServlet.java:278)
	net.sourceforge.stripes.controller.DispatcherServlet.service(DispatcherServlet.java:160)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	net.sourceforge.stripes.controller.StripesFilter.doFilter(StripesFilter.java:260)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	nl.b3p.web.geotools.GeoToolsFilter.doFilter(GeoToolsFilter.java:52)
	nl.b3p.web.filter.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:122)

```
</details>

### What did you expect?
No errors

### Reproduce
How can we reproduce this? 

  1.  load WMTS service `https://geodata.nationaalgeoregister.nl/luchtfoto/rgb/wmts?request=GetCapabilities` into "Gegevens register"
  2. add layer `Luchtfoto Actueel Ortho 25cm RGB` to a new application and save
  3. click the layer
  

### Server log
<details>
<summary>
relevant section of the server log:
</summary>

```

2017-10-02 12:01:24 ERROR net.sourceforge.stripes.util.Log.error(Log.java:82) - Unhandled exception in exception handler.
org.json.JSONException: JSONObject["name"] not found.
	at org.json.JSONObject.get(JSONObject.java:471)
	at org.json.JSONObject.getString(JSONObject.java:717)
	at nl.b3p.viewer.admin.stripes.ApplicationTreeLayerActionBean.loadInfo(ApplicationTreeLayerActionBean.java:126)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.sourceforge.stripes.controller.BeforeAfterMethodInterceptor.invoke(BeforeAfterMethodInterceptor.java:154)
	at net.sourceforge.stripes.controller.BeforeAfterMethodInterceptor.intercept(BeforeAfterMethodInterceptor.java:104)
	at net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:173)
	at org.stripesstuff.plugin.waitpage.WaitPageInterceptor.intercept(WaitPageInterceptor.java:175)
	at net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:173)
	at net.sourceforge.stripes.controller.ExecutionContext.wrap(ExecutionContext.java:86)
	at net.sourceforge.stripes.controller.DispatcherHelper.invokeEventHandler(DispatcherHelper.java:454)
	at net.sourceforge.stripes.controller.DispatcherServlet.invokeEventHandler(DispatcherServlet.java:278)
	at net.sourceforge.stripes.controller.DispatcherServlet.service(DispatcherServlet.java:160)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at net.sourceforge.stripes.controller.StripesFilter.doFilter(StripesFilter.java:260)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at nl.b3p.web.geotools.GeoToolsFilter.doFilter(GeoToolsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at nl.b3p.web.filter.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:122)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:615)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1115)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

```
</details>

**Comment by mprins** [comment]
stepping through the layer details shows to have the following `[{"identifier":"default"}]` for key `wms.styles` in the debugger

looking back into "gegevensregister" now shows the url for the WMS (`https://geodata.nationaalgeoregister.nl/luchtfoto/rgb/service?`)
