### ISSUE TITLE
wmts not loadable

### ISSUE THREAD

**Issue by cvanlith** [flamingo-geocms/flamingo#917]
### Version
5.0.0-SNAPSHOT-c9dc2ea

### Browser info
Google Chrome is up-to-date
Versie 62.0.3202.62 (Officiële build) (64-bits)

### URL
https://flamingo4.b3p.nl/viewer/app/Solparc-Voorzieningen/v1

### Where and/or What
wmts not loadable
http://tile.informatievlaanderen.be/ws/raadpleegdiensten/wmts?request=getcapabilities&service=wmts&version=1.0.0

### What happened
exception

### What did you expect?
loading of wmts in register

### logfiles
2017-10-23 15:40:44 ERROR nl.b3p.viewer.admin.stripes.GeoServiceActionBean.add(GeoServiceActionBean.java:789) - Exception loading tiled service from url http://tile.informatievlaanderen.be/ws/raadpleegdiensten/wmts?request=getcapabilities&service=wmts&version=1.0.0
java.lang.NullPointerException
	at nl.b3p.viewer.config.services.TileService.parseWMTSCapabilities(TileService.java:176)
	at nl.b3p.viewer.config.services.TileService.loadFromUrl(TileService.java:93)

### Reproduce
load above service

**Comment by mprins** [comment]
non-rijksdriehoek service

**Comment by mtoonen** [comment]
Doet het nu wel.
