### ISSUE TITLE
some "attribuutbronnen" can not be removed

### ISSUE THREAD

**Issue by cvanlith** [flamingo-geocms/flamingo#920]
### Version
5.0.0-SNAPSHOT-c9dc2ea

### Browser info
Google Chrome is up-to-date
Versie 62.0.3202.62 (Officiële build) (64-bits)

### URL
https://flamingo4.b3p.nl/viewer-admin

### Where and/or What
some "attribuutbronnen" can not be removed

### What happened
removing some sources does nothing, no feedback, nothing removed

### What did you expect?
source te be removed or feedback on problem, e.g. in use

### Reproduce
try to remove B3P DEMOSERVER BRMO TEST RSGB ORACLE

**Comment by geertplaisier** [comment]
Probably an error in the backend. Locally I'm getting an HTTP500 with some DB exception. This error should be catched and an error should be shown to the user (Cannot remove, is in use?)

**Comment by cvanlith** [comment]
some logging:
2018-12-21 14:32:43 WARN  org.hibernate.util.JDBCExceptionReporter.logExceptions(JDBCExceptionReporter.java:233) - SQL Error: 0, SQLState: 23503
2018-12-21 14:32:43 ERROR org.hibernate.util.JDBCExceptionReporter.logExceptions(JDBCExceptionReporter.java:234) - Batch entry 0 delete from feature_source where id=29 was aborted.  Call getNextException to see the cause.
2018-12-21 14:32:43 WARN  org.hibernate.util.JDBCExceptionReporter.logExceptions(JDBCExceptionReporter.java:233) - SQL Error: 0, SQLState: 23503
2018-12-21 14:32:43 ERROR org.hibernate.util.JDBCExceptionReporter.logExceptions(JDBCExceptionReporter.java:234) - ERROR: update or delete on table "feature_source" violates foreign key constraint "fk481336e324045814" on table "feature_type"
  Detail: Key (id)=(29) is still referenced from table "feature_type".
2018-12-21 14:32:43 WARN  net.sourceforge.stripes.util.Log.warn(Log.java:94) - Unhandled exception caught by the Stripes default exception handler.
javax.persistence.RollbackException: Error while committing the transaction
	at org.hibernate.ejb.TransactionImpl.commit(TransactionImpl.java:93)
	at nl.b3p.viewer.admin.stripes.AttributeSourceActionBean.deleteFeatureSource(AttributeSourceActionBean.java:147)
	at nl.b3p.viewer.admin.stripes.AttributeSourceActionBean.delete(AttributeSourceActionBean.java:126)

**Comment by cvanlith** [comment]
additional logging:
  delete on table "feature_type" violates foreign key constraint "fk7d6832246f7feb1e" on table "file_upload"

**Comment by mtoonen** [comment]
Fixed
