### ISSUE TITLE
flamingo.solr.schedule configuration error

### ISSUE THREAD

**Issue by BaderAhmad** [flamingo-geocms/flamingo#973]
### Version
4.8.1.4

### Where and/or What

viewer-admin solr configuration
### What happened
The solr is working but there is no indexes. When trying to configure  the flamingo.solr.schedule to run periodically in viewer-admin, the viewer-admin doesn't start and we get this error in catalina.out

### Server log
<details><summary>relevant section of the server log:</summary>

```
Jan 15, 2018 10:18:19 AM org.apache.catalina.core.StandardContext startInternal
SEVERE: One or more listeners failed to start. Full details will be found in the appropriate container log file
Jan 15, 2018 10:18:19 AM org.apache.catalina.core.StandardContext startInternal
SEVERE: Context [/viewer-admin] startup failed due to previous errors
Jan 15, 2018 10:18:19 AM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
SEVERE: The web application [/viewer-admin] appears to have started a thread named [Thread-11] but has failed to stop it. This is very likely to create a memory leak.
Jan 15, 2018 10:19:19 AM org.apache.catalina.loader.WebappClassLoaderBase loadClass
INFO: Illegal access: this web application instance has been stopped already.  Could not load org.apache.log4j.spi.ThrowableInformation.  The eventual following stack trace is caused by an error thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access, and has no functional impact.
java.lang.IllegalStateException
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1777)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1735)
        at org.apache.log4j.spi.LoggingEvent.<init>(LoggingEvent.java:165)
        at org.apache.log4j.Category.forcedLog(Category.java:391)
        at org.apache.log4j.Category.log(Category.java:856)
        at org.slf4j.impl.Log4jLoggerAdapter.error(Log4jLoggerAdapter.java:575)
        at org.quartz.core.QuartzScheduler$1.run(QuartzScheduler.java:594)
        at java.lang.Thread.run(Thread.java:745)

Exception in thread "Thread-11" java.lang.NoClassDefFoundError: org/apache/log4j/spi/ThrowableInformation
        at org.apache.log4j.spi.LoggingEvent.<init>(LoggingEvent.java:165)
        at org.apache.log4j.Category.forcedLog(Category.java:391)
        at org.apache.log4j.Category.log(Category.java:856)
        at org.slf4j.impl.Log4jLoggerAdapter.error(Log4jLoggerAdapter.java:575)
        at org.quartz.core.QuartzScheduler$1.run(QuartzScheduler.java:594)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.apache.log4j.spi.ThrowableInformation
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1892)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1735)
        ... 6 more


```

</details>

### Reproduce
How can we reproduce this? 

  1. in viewer-admin change the flamingo.solr.schedule parameter from "-1" into a cron expression and restart tomcat.

**Comment by mprins** [comment]
may be a version conflict in the slf4j libs: 
(Quartz -`org.slf4j:slf4j-api:jar:1.7.7:compile`- and Hadoop -`\- org.slf4j:slf4j-log4j12:jar:1.7.5:runtime`-  have differing versions)...

```
[INFO] Scanning for projects...
[INFO] 
[INFO] Using the MultiThreadedBuilder implementation with a thread count of 4
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building solr-commons 5.0.5-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:3.0.2:tree (default-cli) @ solr-commons ---
[INFO] org.flamingo-mc:solr-commons:jar:5.0.5-SNAPSHOT
[INFO] +- org.geotools:gt-main:jar:18.1:compile
[INFO] |  +- org.geotools:gt-api:jar:18.1:compile
[INFO] |  |  \- org.geotools:gt-referencing:jar:18.1:compile
[INFO] |  |     +- com.googlecode.efficient-java-matrix-library:core:jar:0.26:compile
[INFO] |  |     +- commons-pool:commons-pool:jar:1.5.4:compile
[INFO] |  |     +- jgridshift:jgridshift:jar:1.0:compile
[INFO] |  |     \- net.sf.geographiclib:GeographicLib-Java:jar:1.44:compile
[INFO] |  +- com.vividsolutions:jts-core:jar:1.14.0:compile
[INFO] |  +- org.jdom:jdom:jar:1.1.3:compile
[INFO] |  \- javax.media:jai_core:jar:1.1.3:compile
[INFO] +- org.apache.solr:solr-solrj:jar:4.6.0:compile
[INFO] |  +- org.apache.zookeeper:zookeeper:jar:3.4.5:compile
[INFO] |  +- commons-io:commons-io:jar:2.6:compile
[INFO] |  +- org.noggit:noggit:jar:0.5:compile
[INFO] |  +- org.apache.httpcomponents:httpclient:jar:4.5.4:compile
[INFO] |  |  +- org.apache.httpcomponents:httpcore:jar:4.4.7:compile
[INFO] |  |  \- commons-codec:commons-codec:jar:1.10:compile
[INFO] |  +- org.apache.httpcomponents:httpmime:jar:4.5.4:compile
[INFO] |  \- org.codehaus.woodstox:wstx-asl:jar:3.2.7:runtime
[INFO] +- commons-logging:commons-logging:jar:1.2:compile
[INFO] +- javax.servlet:javax.servlet-api:jar:3.0.1:provided
[INFO] +- org.quartz-scheduler:quartz:jar:2.3.0:compile
[INFO] |  +- com.mchange:c3p0:jar:0.9.5.2:compile
[INFO] |  +- com.mchange:mchange-commons-java:jar:0.2.11:compile
[INFO] |  +- com.zaxxer:HikariCP-java6:jar:2.3.13:compile
[INFO] |  \- org.slf4j:slf4j-api:jar:1.7.7:compile
[INFO] +- org.stripesstuff:stripersist:jar:1.0.3:compile
[INFO] +- org.flamingo-mc:viewer-config-persistence:jar:5.0.5-SNAPSHOT:compile
[INFO] |  +- org.apache.commons:commons-lang3:jar:3.7:compile
[INFO] |  +- commons-beanutils:commons-beanutils-core:jar:1.8.3:compile
[INFO] |  +- org.json:json:jar:20160810:compile
[INFO] |  +- org.flamingo-mc:viewer-commons:jar:5.0.5-SNAPSHOT:compile
[INFO] |  |  +- com.googlecode.json-simple:json-simple:jar:1.1.1:compile
[INFO] |  |  +- org.geotools:gt-data:jar:18.1:compile
[INFO] |  |  +- org.geotools:gt-jdbc:jar:18.1:compile
[INFO] |  |  |  \- commons-dbcp:commons-dbcp:jar:1.4:compile
[INFO] |  |  +- org.geotools:gt-epsg-wkt:jar:18.1:compile
[INFO] |  |  +- com.google.javascript:closure-compiler:jar:v20161201:compile
[INFO] |  |  |  +- com.google.javascript:closure-compiler-externs:jar:v20161201:compile
[INFO] |  |  |  +- args4j:args4j:jar:2.33:compile
[INFO] |  |  |  +- com.google.guava:guava:jar:20.0:compile
[INFO] |  |  |  +- com.google.protobuf:protobuf-java:jar:3.0.2:compile
[INFO] |  |  |  +- com.google.code.gson:gson:jar:2.7:compile
[INFO] |  |  |  +- com.google.code.findbugs:jsr305:jar:3.0.1:compile
[INFO] |  |  |  \- com.google.jsinterop:jsinterop-annotations:jar:1.0.0:compile
[INFO] |  |  +- org.apache.solr:solr-core:jar:4.6.0:compile
[INFO] |  |  |  +- org.apache.lucene:lucene-codecs:jar:4.6.0:compile
[INFO] |  |  |  +- org.apache.lucene:lucene-analyzers-common:jar:4.6.0:compile
[INFO] |  |  |  +- org.apache.lucene:lucene-analyzers-kuromoji:jar:4.6.0:compile
[INFO] |  |  |  +- org.apache.lucene:lucene-analyzers-phonetic:jar:4.6.0:compile
[INFO] |  |  |  +- org.apache.lucene:lucene-highlighter:jar:4.6.0:compile
[INFO] |  |  |  +- org.apache.lucene:lucene-memory:jar:4.6.0:compile
[INFO] |  |  |  +- org.apache.lucene:lucene-misc:jar:4.6.0:compile
[INFO] |  |  |  +- org.apache.lucene:lucene-join:jar:4.6.0:compile
[INFO] |  |  |  +- org.apache.lucene:lucene-queryparser:jar:4.6.0:compile
[INFO] |  |  |  +- org.apache.lucene:lucene-spatial:jar:4.6.0:compile
[INFO] |  |  |  |  \- com.spatial4j:spatial4j:jar:0.3:compile
[INFO] |  |  |  +- org.apache.lucene:lucene-suggest:jar:4.6.0:compile
[INFO] |  |  |  +- org.apache.lucene:lucene-grouping:jar:4.6.0:compile
[INFO] |  |  |  +- org.apache.lucene:lucene-queries:jar:4.6.0:compile
[INFO] |  |  |  +- com.carrotsearch:hppc:jar:0.5.2:compile
[INFO] |  |  |  +- com.googlecode.concurrentlinkedhashmap:concurrentlinkedhashmap-lru:jar:1.2:compile
[INFO] |  |  |  +- commons-cli:commons-cli:jar:1.2:compile
[INFO] |  |  |  +- joda-time:joda-time:jar:2.2:compile
[INFO] |  |  |  +- org.apache.hadoop:hadoop-annotations:jar:2.2.0:compile
[INFO] |  |  |  |  \- jdk.tools:jdk.tools:jar:1.6:system
[INFO] |  |  |  +- org.apache.hadoop:hadoop-auth:jar:2.2.0:compile
[INFO] |  |  |  |  \- org.slf4j:slf4j-log4j12:jar:1.7.5:runtime
[INFO] |  |  |  +- org.apache.hadoop:hadoop-common:jar:2.2.0:compile
[INFO] |  |  |  |  \- org.apache.commons:commons-compress:jar:1.4.1:compile
[INFO] |  |  |  |     \- org.tukaani:xz:jar:1.0:compile
[INFO] |  |  |  +- org.apache.hadoop:hadoop-hdfs:jar:2.2.0:compile
[INFO] |  |  |  \- commons-lang:commons-lang:jar:2.6:compile
[INFO] |  |  +- org.apache.httpcomponents:fluent-hc:jar:4.5.4:compile
[INFO] |  |  \- org.apache.httpcomponents:httpclient-cache:jar:4.5.4:compile
[INFO] |  +- org.flamingo-mc:web-commons:jar:5.0.5-SNAPSHOT:compile
[INFO] |  |  +- net.sourceforge.stripes:stripes:jar:1.6.0:compile
[INFO] |  |  |  \- log4j:log4j:jar:1.2.17:compile
[INFO] |  |  \- org.geotools:gt-metadata:jar:18.1:compile
[INFO] |  |     \- org.geotools:gt-opengis:jar:18.1:compile
[INFO] |  |        \- net.java.dev.jsr-275:jsr-275:jar:1.0-beta-2:compile
[INFO] |  +- org.geotools:gt-wms:jar:18.1:compile
[INFO] |  |  +- org.geotools:gt-coverage:jar:18.1:compile
[INFO] |  |  |  +- javax.media:jai_imageio:jar:1.1:compile
[INFO] |  |  |  +- it.geosolutions.imageio-ext:imageio-ext-tiff:jar:1.1.18:compile
[INFO] |  |  |  |  +- it.geosolutions.imageio-ext:imageio-ext-utilities:jar:1.1.18:compile
[INFO] |  |  |  |  +- it.geosolutions.imageio-ext:imageio-ext-geocore:jar:1.1.18:compile
[INFO] |  |  |  |  |  \- it.geosolutions.imageio-ext:imageio-ext-streams:jar:1.1.18:compile
[INFO] |  |  |  |  \- javax.media:jai_codec:jar:1.1.3:compile
[INFO] |  |  |  +- com.vividsolutions:jts-example:jar:1.14.0:compile
[INFO] |  |  |  |  \- com.vividsolutions:jts-io:jar:1.14.0:compile
[INFO] |  |  |  +- org.jaitools:jt-zonalstats:jar:1.4.0:compile
[INFO] |  |  |  +- org.jaitools:jt-utils:jar:1.4.0:compile
[INFO] |  |  |  +- it.geosolutions.jaiext.affine:jt-affine:jar:1.0.16:compile
[INFO] |  |  |  +- it.geosolutions.jaiext.algebra:jt-algebra:jar:1.0.16:compile
[INFO] |  |  |  +- it.geosolutions.jaiext.bandmerge:jt-bandmerge:jar:1.0.16:compile
[INFO] |  |  |  +- it.geosolutions.jaiext.bandselect:jt-bandselect:jar:1.0.16:compile
[INFO] |  |  |  +- it.geosolutions.jaiext.bandcombine:jt-bandcombine:jar:1.0.16:compile
[INFO] |  |  |  +- it.geosolutions.jaiext.border:jt-border:jar:1.0.16:compile
[INFO] |  |  |  +- it.geosolutions.jaiext.buffer:jt-buffer:jar:1.0.16:compile
[INFO] |  |  |  +- it.geosolutions.jaiext.crop:jt-crop:jar:1.0.16:compile
[INFO] |  |  |  +- it.geosolutions.jaiext.iterators:jt-iterators:jar:1.0.16:compile
[INFO] |  |  |  +- it.geosolutions.jaiext.lookup:jt-lookup:jar:1.0.16:compile
[INFO] |  |  |  +- it.geosolutions.jaiext.mosaic:jt-mosaic:jar:1.0.16:compile
[INFO] |  |  |  +- it.geosolutions.jaiext.nullop:jt-nullop:jar:1.0.16:compile
[INFO] |  |  |  +- it.geosolutions.jaiext.rescale:jt-rescale:jar:1.0.16:compile
[INFO] |  |  |  +- it.geosolutions.jaiext.scale:jt-scale:jar:1.0.16:compile
[INFO] |  |  |  +- it.geosolutions.jaiext.stats:jt-stats:jar:1.0.16:compile
[INFO] |  |  |  +- it.geosolutions.jaiext.translate:jt-translate:jar:1.0.16:compile
[INFO] |  |  |  +- it.geosolutions.jaiext.utilities:jt-utilities:jar:1.0.16:compile
[INFO] |  |  |  +- it.geosolutions.jaiext.warp:jt-warp:jar:1.0.16:compile
[INFO] |  |  |  +- it.geosolutions.jaiext.zonal:jt-zonal:jar:1.0.16:compile
[INFO] |  |  |  +- it.geosolutions.jaiext.binarize:jt-binarize:jar:1.0.16:compile
[INFO] |  |  |  +- it.geosolutions.jaiext.format:jt-format:jar:1.0.16:compile
[INFO] |  |  |  +- it.geosolutions.jaiext.colorconvert:jt-colorconvert:jar:1.0.16:compile
[INFO] |  |  |  +- it.geosolutions.jaiext.errordiffusion:jt-errordiffusion:jar:1.0.16:compile
[INFO] |  |  |  +- it.geosolutions.jaiext.orderdither:jt-orderdither:jar:1.0.16:compile
[INFO] |  |  |  +- it.geosolutions.jaiext.colorindexer:jt-colorindexer:jar:1.0.16:compile
[INFO] |  |  |  +- it.geosolutions.jaiext.imagefunction:jt-imagefunction:jar:1.0.16:compile
[INFO] |  |  |  +- it.geosolutions.jaiext.piecewise:jt-piecewise:jar:1.0.16:compile
[INFO] |  |  |  +- it.geosolutions.jaiext.classifier:jt-classifier:jar:1.0.16:compile
[INFO] |  |  |  +- it.geosolutions.jaiext.rlookup:jt-rlookup:jar:1.0.16:compile
[INFO] |  |  |  \- it.geosolutions.jaiext.vectorbin:jt-vectorbin:jar:1.0.16:compile
[INFO] |  |  +- commons-httpclient:commons-httpclient:jar:3.1:compile
[INFO] |  |  +- org.geotools:gt-xml:jar:18.1:compile
[INFO] |  |  |  \- org.apache.xml:xml-commons-resolver:jar:1.2:compile
[INFO] |  |  \- org.geotools:gt-render:jar:18.1:compile
[INFO] |  +- org.geotools:gt-wfs-ng:jar:18.1:compile
[INFO] |  |  +- org.geotools:gt-complex:jar:18.1:compile
[INFO] |  |  |  \- org.geotools:gt-app-schema-resolver:jar:18.1:compile
[INFO] |  |  +- org.geotools.xsd:gt-xsd-gml3:jar:18.1:compile
[INFO] |  |  |  +- org.geotools.xsd:gt-xsd-core:jar:18.1:compile
[INFO] |  |  |  |  +- picocontainer:picocontainer:jar:1.2:compile
[INFO] |  |  |  |  +- commons-jxpath:commons-jxpath:jar:1.3:compile
[INFO] |  |  |  |  \- org.eclipse.xsd:org.eclipse.xsd:jar:2.12.0:compile
[INFO] |  |  |  \- org.geotools.xsd:gt-xsd-gml2:jar:18.1:compile
[INFO] |  |  +- org.geotools.xsd:gt-xsd-wfs:jar:18.1:compile
[INFO] |  |  |  +- org.geotools.xsd:gt-xsd-filter:jar:18.1:compile
[INFO] |  |  |  +- org.geotools.xsd:gt-xsd-fes:jar:18.1:compile
[INFO] |  |  |  \- org.geotools.xsd:gt-xsd-ows:jar:18.1:compile
[INFO] |  |  |     \- org.geotools.ogc:net.opengis.ows:jar:18.1:compile
[INFO] |  |  +- org.geotools.ogc:net.opengis.wfs:jar:18.1:compile
[INFO] |  |  |  +- org.geotools.ogc:org.w3.xlink:jar:18.1:compile
[INFO] |  |  |  +- org.geotools.ogc:net.opengis.fes:jar:18.1:compile
[INFO] |  |  |  +- org.eclipse.emf:org.eclipse.emf.common:jar:2.12.0:compile
[INFO] |  |  |  +- org.eclipse.emf:org.eclipse.emf.ecore:jar:2.12.0:compile
[INFO] |  |  |  \- org.eclipse.emf:org.eclipse.emf.ecore.xmi:jar:2.12.0:compile
[INFO] |  |  +- org.geotools:gt-cql:jar:18.1:compile
[INFO] |  |  +- xpp3:xpp3_min:jar:1.1.4c:compile
[INFO] |  |  \- xmlunit:xmlunit:jar:1.3:compile
[INFO] |  +- org.geotools.jdbc:gt-jdbc-oracle:jar:18.1:compile
[INFO] |  +- org.geotools.jdbc:gt-jdbc-postgis:jar:18.1:compile
[INFO] |  |  \- org.postgresql:postgresql:jar:42.1.1:compile
[INFO] |  +- org.javassist:javassist:jar:3.22.0-CR2:compile
[INFO] |  +- org.hibernate:hibernate-core:jar:3.6.10.Final:compile
[INFO] |  |  +- antlr:antlr:jar:2.7.6:compile
[INFO] |  |  +- commons-collections:commons-collections:jar:3.1:compile
[INFO] |  |  +- dom4j:dom4j:jar:1.6.1:compile
[INFO] |  |  +- org.hibernate:hibernate-commons-annotations:jar:3.2.0.Final:compile
[INFO] |  |  +- org.hibernate.javax.persistence:hibernate-jpa-2.0-api:jar:1.0.1.Final:compile
[INFO] |  |  \- javax.transaction:jta:jar:1.1:compile
[INFO] |  +- org.hibernate:hibernate-entitymanager:jar:3.6.10.Final:compile
[INFO] |  |  \- cglib:cglib:jar:2.2:compile
[INFO] |  |     \- asm:asm:jar:3.1:compile
[INFO] |  \- org.hsqldb:hsqldb:jar:2.4.0:compile
[INFO] \- junit:junit:jar:4.12:compile
[INFO]    \- org.hamcrest:hamcrest-core:jar:1.3:compile
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.618 s (Wall Clock)
[INFO] Finished at: 2018-01-15T11:29:15+01:00
[INFO] Final Memory: 22M/379M
[INFO] ------------------------------------------------------------------------

```

**Comment by mprins** [comment]
can no longer reproduce

**Comment by mprins** [comment]
can no longer reproduce
