### ISSUE TITLE
viewer fails to start without debug=true option

### ISSUE THREAD

**Issue by mprins** [flamingo-geocms/flamingo#981]
### Version
Which version of flamingo do you use: 5.0.5-SNAPSHOT

### Browser info
both FF and chrome

### URL

http://localhost:7081/viewer/app/mantis-6952?debug=true

### Where and/or What

viewer

### What happened

viewer fails to start unless `?debug=true` is appended to the url

### What did you expect?

viewer should start without setting debug option

may be a regression as a result of updating the closure-compiler in a6796ac1bea449f95127466422f96fb87b3f6893

**Comment by mprins** [comment]
another viewer: https://test.flamingo4.nl/viewer/app/Extended_feature_info

chrome stack trace:
```
ext-all.js:22 Uncaught TypeError: Cannot read property 'apply' of null
    at F.callParent (https://test.flamingo4.nl/viewer/extjs/ext-all.js:22:92423)
    at F.addDelegatedListener (https://test.flamingo4.nl/viewer/viewer-html/viewer-min.js:1684:12)
    at F.subscribe (https://test.flamingo4.nl/viewer/extjs/ext-all.js:22:249147)
    at F.addListener (https://test.flamingo4.nl/viewer/extjs/ext-all.js:22:143957)
    at F.addListener (https://test.flamingo4.nl/viewer/extjs/ext-all.js:22:219470)
    at F.doAddListener (https://test.flamingo4.nl/viewer/extjs/ext-all.js:22:158760)
    at F.doAddListener (https://test.flamingo4.nl/viewer/extjs/ext-all.js:22:308081)
    at F.addListener (https://test.flamingo4.nl/viewer/extjs/ext-all.js:22:154977)
    at F.e.(anonymous function) [as on] (https://test.flamingo4.nl/viewer/extjs/ext-all.js:22:91842)
    at Ext.onInternalReady.priority (https://test.flamingo4.nl/viewer/extjs/ext-all.js:22:396468)
```

FF stack trace:
```
TypeError: access to strict mode caller function is censored ext-all.js:22:92313
	callParent https://test.flamingo4.nl/viewer/extjs/ext-all.js:22:92313
	constructor https://test.flamingo4.nl/viewer/viewer-html/viewer-min.js:145:3
	g https://test.flamingo4.nl/viewer/extjs/ext-all.js:22:95037
	loadViewerController https://test.flamingo4.nl/viewer/viewer-html/viewer-min.js:66:34
	processAppConfig/< https://test.flamingo4.nl/viewer/viewer-html/viewer-min.js:22:5
	invoke https://test.flamingo4.nl/viewer/extjs/ext-all.js:22:132618
	on https://test.flamingo4.nl/viewer/extjs/ext-all.js:22:133270
	Ext.onReady https://test.flamingo4.nl/viewer/extjs/ext-all.js:22:135158
	processAppConfig https://test.flamingo4.nl/viewer/viewer-html/viewer-min.js:21:3
	success https://test.flamingo4.nl/viewer/viewer-html/viewer-min.js:12:17
	callback https://test.flamingo4.nl/viewer/extjs/ext-all.js:22:71527
	onComplete https://test.flamingo4.nl/viewer/extjs/ext-all.js:22:183389
	onStateChange https://test.flamingo4.nl/viewer/extjs/ext-all.js:22:182917
	bind/< https://test.flamingo4.nl/viewer/extjs/ext-all.js:22:60840

```
